// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo_api.Data;

#nullable disable

namespace todo_api.Data.Migrations
{
    [DbContext(typeof(TodoProjectDbContext))]
    [Migration("20240914153009_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("todo_api.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Complete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Complete = false,
                            Description = "SomeDesc",
                            Title = "Walk"
                        },
                        new
                        {
                            Id = 2,
                            Complete = false,
                            Description = "Drink",
                            Title = "Water"
                        },
                        new
                        {
                            Id = 3,
                            Complete = false,
                            Description = "FinishIt",
                            Title = "ZellaProject"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
